-- task 1 
-- SELECT * FROM employees

-- task 2
-- DESCRIBE EMPLOYEES;

-- task 3
-- SELECT LAST_NAME, SALARY FROM EMPLOYEES

-- task 4
-- SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES

-- task 5
-- SELECT LAST_NAME, SALARY / 30 AS DAILY_WAGE, SALARY AS MONTHLY_SALARY, SALARY * 12 AS ANNUAL_SALARY FROM EMPLOYEES

-- task 6
-- SELECT LAST_NAME AS "Last Name",
-- SALARY / 30 AS "Dialy wage",
-- SALARY AS "Monthly salary",
-- SALARY * 12 AS "Annual salary" FROM EMPLOYEES

-- task 7 
-- SELECT LAST_NAME || ' - Department: ' || DEPARTMENT_ID AS EMPLOYEE_INFO FROM EMPLOYEES
-- practice
-- SELECT FIRST_NAME || ' ' || LAST_NAME || q'['s phone number: ]' || PHONE_NUMBER || ' ' || 'works as ' || JOB_TITLE  AS "Employees' contact data" FROM EMPLOYEES E, JOBS J WHERE J.JOB_ID = E.JOB_ID

-- task 8
-- SELECT DISTINCT FIRST_NAME FROM EMPLOYEES

-- task 9 
-- SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES ORDER BY LAST_NAME, DEPARTMENT_ID, SALARY;


-- task 10 -----------------------------------------------------
-- SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (40, 50, 80);

-- SELECT * FROM EMPLOYEES WHERE (DEPARTMENT_ID = 40 OR DEPARTMENT_ID = 50 OR DEPARTMENT_ID = 80);

-- SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID IN (40,50,80))
----------------------------------------------------------------

-- task 11
-- SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL

-- task 12 
-- SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE '%CLERK%'

-- task 13
-- SELECT COUNT(*) AS NUM_OF_EMPLOYEES,  DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID

-- task 14
-- SELECT DEPARTMENT_ID, COUNT(*) AS NUM_OF_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(*)>10

-- task 15
-- SELECT DEPARTMENT_ID, JOB_ID, COUNT(*) AS NUMBER_OF_EMPLOYEES FROM EMPLOYEES GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID)

-- task 16
-- SELECT JOB_ID, MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY JOB_ID

-- task 17
-- SELECT FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=30
-- INTERSECT
-- SELECT FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=60
  
-- task 18
-- (A)
-- SELECT * FROM EMPLOYEES, DEPARTMENTS
-- SELECT * FROM EMPLOYEES CROSS JOIN DEPARTMENTS

-- (B)
-- SELECT * FROM EMPLOYEES E, DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID

-- (C)
-- SELECT * FROM EMPLOYEES NATURAL JOIN DEPARTMENTS


-- task 19
-- SELECT E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY, J.JOB_TITLE, J.MIN_SALARY, J.MAX_SALARY 
-- FROM EMPLOYEES E 
-- JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- JOIN JOBS J ON E.JOB_ID = J.JOB_ID
-- WHERE J.MIN_SALARY > 5000 AND J.MAX_SALARY<13000


-- task 20
-- SELECT LAST_NAME FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES)

-- task 21
-- SELECT DEPARTMENT_ID, LAST_NAME, HIRE_DATE FROM EMPLOYEES E WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID)

-- task 22
--1) SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID WHERE E.EMPLOYEE_ID IS NULL
--2) SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL)

-- task 23
--1) SELECT DEPARTMENT_ID, SUM(SALARY + SALARY * NVL(COMMISSION_PCT, 0)) AS TOTAL_COST FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY TOTAL_COST DESC FETCH FIRST 1 ROW ONLY

--2) SELECT department_id, total_cost FROM (
--     SELECT department_id,
--            SUM(salary + salary * NVL(commission_pct, 0)) AS total_cost
--     FROM employees
--     GROUP BY department_id
--     ORDER BY total_cost DESC
-- ) WHERE ROWNUM = 1;




